# Generated by Django 5.0 on 2023-12-22 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('account_type', models.CharField(choices=[('Organization', 'Organization')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_type', models.CharField(choices=[('Passport', 'Passport')], max_length=20)),
                ('id_verified', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('date_of_birth', models.DateField()),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('gender', models.CharField(choices=[('Female', 'Female')], max_length=10)),
                ('profession', models.CharField(max_length=255)),
                ('blood_group', models.CharField(choices=[('A-', 'A-')], max_length=5)),
                ('current_location', models.CharField(max_length=255)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
