# Generated by Django 5.0 on 2023-12-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'Ab+'), (6, 'Ab-'), (7, 'O+'), (8, 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_card_type',
            field=models.CharField(choices=[(1, 'Nid'), (2, 'Passport'), (3, 'Driving')], max_length=20),
        ),
    ]
