# Generated by Django 5.0 on 2023-12-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_blood_group_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Full_Name',
            new_name='full_Name',
        ),
    ]
